name: Rebase

on:
  schedule: [cron: '0 0 * * *']
  workflow_dispatch:

jobs:
  build:
    name: Automatic rebase
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Fetch EvolutionX repo
      run: |
        git config user.name "sahaymihir"
        git config user.email "mihir.sahay0123@hotmail.com"
        git fetch https://github.com/Evolution-X/frameworks_base snow

    - name: Rebase
      run: |
        git rebase FETCH_HEAD
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        force: true
        github_token: ${{ secrets.GHTOKEN }}
